

supervision: True
# supervision: False


# agent_name: "LevineT_2"
agent_name: "LevineT_3"
# agent_name: "LevineT_1"
# agent_name: "BaselineAgent_1"

# map_name: "f1_aut_wide"
# map_name: "levine_blocked"
map_name: "levine_2nd"
# map_name: "columbia_small"

sim_steps: 5

n_train_steps: 50000
n_test_laps: 2

show_train: True
# show_train: False
show_test: True
# show_test: False
verbose: True
# verbose: False

