

supervision: True
# supervision: False

# planner: pure_pursuit 
planner: random 
# planner: agent 

agent_name: "SafetyTrainingAgent_4"

# map_name: "f1_aut_wide"
map_name: "levine_blocked"
# map_name: "columbia_small"

sim_steps: 5

n_train_steps: 4000
n_test_laps: 1

show_train: True
# show_train: False
show_test: True
# show_test: False
verbose: True
# verbose: False
