
config_filename: "config_file"
n_laps: 6

# supervision: True
supervision: False

# planner: pure_pursuit 
# planner: random 
planner: agent 

agent_name: "SafetyTrainingAgent_4"

map_name: "columbia_small"

test_n: 10
sim_steps: 5

